{% set name = "mongoengine" %}
{% set version = "0.14.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4608ffce39bc95f9874b094e9dfe0153245e18957ba8df8dddcbc7c6bc43a020" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pymongo >=2.7.1
    - six

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - pmlandwehr
