{% set name = "mongoengine" %}
{% set version = "0.15.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2ecc60f50d9f85d4ae7e2e8bd1dc19778af65d2883d5ad6d658d77f1560059d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pymongo >=2.7.1
    - six

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - pmlandwehr
