travis:
  secure:
    BINSTAR_TOKEN: lN7abM1Mv0z5QY9nyUHEkbuuR0/eqpeJjyY7q5fedIHwSpWx5HILvL8m8/qBU816th0ZxhTOerSr6NaouI24gE9eQkhj4A40PWuAh7qelJ80400fwaRBcj73h4w1FuKAoyVmMswo6iXb9nqDA9FWMnllkHwEtkerulxG0WxegSOklmunBvRzMM1nHi1qeZk9/31eqjqQq9CEN+QElsqth/cLr1lwAzTYzFo05RDZJZc8xH1N00dDf0tyPHDqQ8WjZK1UyQOIvfyagann8/GIcN2rRyYomA94FF8vtfdSv57q0BLI5Tr1RBJ91JC42WKmnbwFksmppE6SDDbLUqfR7I9hNM/j1WNVgU6+UQuVGBBpBMFfh3Fip2jjljZRgAncd644T6d3EneWE0FpEVt7+uC+LBTi3CcVKYEgaxbLToo/S/O0GZn03zxtL0FYTkPntLxhBes5k42O/zl5BAcoSRiR6VFmPkgSO5GRKdhsAYV2cBAW88KjKRlYmUAH4aPN+licysIjr9D3XjiyqvcsYDClgM0R4CGM08E6yyLrVBSu26IAIi8pbKB7dUAW0rKk2AQuJeCz5iM8CGLAI4bPvY+I9P70KE2fZ6f2IkNw90GOlN0apVd0s6fAdsWZ1LOvVzhvtCUQvlS+v2NEz1ZkxR+T13ecL5Hq6HbtJxZbsk4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
