travis:
  secure:
    BINSTAR_TOKEN: iVbOpWSehYRnVnVR59JidRoyty0jDAvRjZHniJllp/dwav5EHmTyGhEAtppPhd+bTvMkc6zgH310f2ZhNA+U1jxyWP0Qr37Ka1O7QQoDsq+6BQOvcOVO1xpQrwPRoXLjfA/PRqLErTV0vik6dWzFjCGf8PVFu0oseaV37VoC1XAC4PRS8Q5pq8jTO3s6j9Z19qVUQpvY6tZKCx+rkQvtO3/4XSVpel7dt30pGlmlHH1QPnUoDBJ6JNA/6uOI1B/MSYVpVj3Ddt2EG9K05aft3nXN5uCM2nrHYW7hXVNirnJ9TT6/xvdZ1052hvTNvfrt+ZT55EKrzNP7g4FBnJ0MU3YqPWLua4SDzWgH45MPbryJdwSZluinPMgzuPwpEExxhk9Ou7Sk5Dr/l5xyowaIzv0otLbdKLiARJzvTkKLHj08tqx3phbEg7x+lIE19xHaFy5K6p4T/EW60f1yItMvEgVy/pZq0apTA12/hL5G+hqyUhIerjtp3vl/4extAOjfmKRphpR6/IaW2YOIOySr4i2Q3kOi0U7pg0AXDEa/aeegvfpezW9Ora0VDdPAGWIgCktFGCIr0JRzupMT6jIEMMhSTr3oUv2jpxiyXRDQPeumnJIr4IZd6o1mTCTSLIDxaF+Jke7DCemkp2LdwiemPr2mny+BHWCD1EE2D9E7UVM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
